name: Release

on:
  push:
    tags:
      - "*"

jobs:

  #  requires apple developer account
  release-mac:
    name: "Release Development MacOS"
    runs-on: macos-latest

    steps:

      - name: Checkout wallet
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install node dependencies
        run: |
          npm install
          npm i -g electron-builder
          npm i -g electron-packager

      - name: Download Artifact Wallet
        run: |
          cd ./dist
          
          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/PandoraPay-wallet/releases/download/development/wallet-build.zip > wallet-build.zip
          unzip wallet-build.zip
          rm wallet-build.zip

      - name: Download Artifact Electron Helper
        run: |
          cd ./helper
          
          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/go-pandora-pay/releases/download/development/artifact-electron-helper.zip > artifact-electron-helper.zip
          unzip artifact-electron-helper.zip
          rm artifact-electron-helper.zip

      - name: release builder
        run: electron-builder -m --config electron-builder.js --publish never -c.mac.identity=null

      - name: Upload mac builds
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-windows
          path: |
            ./bin/builder/pandora-cash-wallet-*
          retention-days: 3


  release-win:
    name: "Release Development Windows"
    runs-on: windows-latest

    steps:

      - name: Checkout wallet
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install node dependencies
        run: |
          npm install
          npm i -g electron-builder
          npm i -g electron-packager

      - name: Download Artifact Wallet
        shell: powershell
        run: |
          cd dist
          Invoke-WebRequest -Uri "https://github.com/pandora-cash/PandoraPay-wallet/releases/download/development/wallet-build.zip" -OutFile "wallet-build.zip"
          7z x -y wallet-build.zip
          del wallet-build.zip

      - name: Download Artifact Electron Helper
        run: |
          cd helper
          Invoke-WebRequest -Uri "https://github.com/pandora-cash/go-pandora-pay/releases/download/development/artifact-electron-helper.zip" -OutFile "artifact-electron-helper.zip"
          7z x -y artifact-electron-helper.zip
          del artifact-electron-helper.zip                    

      - name: release builder
        run: electron-builder -w --config electron-builder.js --publish never

      - name: Upload windows builds
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-windows
          path: |
            ./bin/builder/pandora-cash-wallet-win-*
          retention-days: 3

  release-linux:
    name: "Release Development Linux"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout wallet
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          sudo apt-get install rpm

      - name: Install node dependencies
        run: |
          npm install
          npm i -g electron-builder
          npm i -g electron-packager

      - name: Download Artifact Wallet
        run: |
          cd ./dist

          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/PandoraPay-wallet/releases/download/development/wallet-build.zip > wallet-build.zip
          unzip wallet-build.zip
          rm wallet-build.zip
          
          cd ..

      - name: Download Artifact Electron Helper
        run: |
          cd ./helper

          curl -L  -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" https://github.com/pandora-cash/go-pandora-pay/releases/download/development/artifact-electron-helper.zip > artifact-electron-helper.zip
          unzip artifact-electron-helper.zip
          rm artifact-electron-helper.zip
          
          cd ..

      # release packager for darwin
      - name: release packager
        run: bash release-packager.sh no-build no-release-windows no-release-linux

      - name: Display structure of release packager
        run: |
          ls
          rm -r -- ./*/
        working-directory: bin/packager

      - name: Upload windows packager builds
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-packager
          path: |
            ./bin/packager/pandora-cash-wallet-*
          retention-days: 3

      - name: release builder
        run: electron-builder -l --config electron-builder.js --publish never

      - name: Upload linux builds
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-windows
          path: |
            ./bin/builder/pandora-cash-wallet-*
          retention-days: 3

  release-upload:
    name: "Upload release"
    needs: [ release-win, release-mac, release-linux ]
    runs-on: ubuntu-latest

    steps:

      - name: Checkout wallet
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: bin/artifacts

      - name: Display structure of artifacts
        run: ls -R
        working-directory: bin/artifacts

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            ./bin/artifacts/**
